#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mobilBankacilik")]
	public partial class MusteriDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKrediBilgileri(KrediBilgileri instance);
    partial void UpdateKrediBilgileri(KrediBilgileri instance);
    partial void DeleteKrediBilgileri(KrediBilgileri instance);
    partial void InsertKullaniciBilgileri(KullaniciBilgileri instance);
    partial void UpdateKullaniciBilgileri(KullaniciBilgileri instance);
    partial void DeleteKullaniciBilgileri(KullaniciBilgileri instance);
    partial void InsertHesapBilgileri(HesapBilgileri instance);
    partial void UpdateHesapBilgileri(HesapBilgileri instance);
    partial void DeleteHesapBilgileri(HesapBilgileri instance);
    #endregion
		
		public MusteriDataDataContext() : 
				base(global::DAL.Properties.Settings.Default.mobilBankacilikConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusteriDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KrediBilgileri> KrediBilgileri
		{
			get
			{
				return this.GetTable<KrediBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<KullaniciBilgileri> KullaniciBilgileri
		{
			get
			{
				return this.GetTable<KullaniciBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<HesapBilgileri> HesapBilgileri
		{
			get
			{
				return this.GetTable<HesapBilgileri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KrediBilgileri")]
	public partial class KrediBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KrediNO;
		
		private int _KrediMiktari;
		
		private int _KrediVade;
		
		private int _KrediFaiz;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKrediNOChanging(int value);
    partial void OnKrediNOChanged();
    partial void OnKrediMiktariChanging(int value);
    partial void OnKrediMiktariChanged();
    partial void OnKrediVadeChanging(int value);
    partial void OnKrediVadeChanged();
    partial void OnKrediFaizChanging(int value);
    partial void OnKrediFaizChanged();
    #endregion
		
		public KrediBilgileri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KrediNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KrediNO
		{
			get
			{
				return this._KrediNO;
			}
			set
			{
				if ((this._KrediNO != value))
				{
					this.OnKrediNOChanging(value);
					this.SendPropertyChanging();
					this._KrediNO = value;
					this.SendPropertyChanged("KrediNO");
					this.OnKrediNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KrediMiktari", DbType="Int NOT NULL")]
		public int KrediMiktari
		{
			get
			{
				return this._KrediMiktari;
			}
			set
			{
				if ((this._KrediMiktari != value))
				{
					this.OnKrediMiktariChanging(value);
					this.SendPropertyChanging();
					this._KrediMiktari = value;
					this.SendPropertyChanged("KrediMiktari");
					this.OnKrediMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KrediVade", DbType="Int NOT NULL")]
		public int KrediVade
		{
			get
			{
				return this._KrediVade;
			}
			set
			{
				if ((this._KrediVade != value))
				{
					this.OnKrediVadeChanging(value);
					this.SendPropertyChanging();
					this._KrediVade = value;
					this.SendPropertyChanged("KrediVade");
					this.OnKrediVadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KrediFaiz", DbType="Int NOT NULL")]
		public int KrediFaiz
		{
			get
			{
				return this._KrediFaiz;
			}
			set
			{
				if ((this._KrediFaiz != value))
				{
					this.OnKrediFaizChanging(value);
					this.SendPropertyChanging();
					this._KrediFaiz = value;
					this.SendPropertyChanged("KrediFaiz");
					this.OnKrediFaizChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KullaniciBilgileri")]
	public partial class KullaniciBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KayitNO;
		
		private int _HesapNO;
		
		private string _MusteriAd;
		
		private string _MusteriSoyad;
		
		private int _MusteriYas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKayitNOChanging(int value);
    partial void OnKayitNOChanged();
    partial void OnHesapNOChanging(int value);
    partial void OnHesapNOChanged();
    partial void OnMusteriAdChanging(string value);
    partial void OnMusteriAdChanged();
    partial void OnMusteriSoyadChanging(string value);
    partial void OnMusteriSoyadChanged();
    partial void OnMusteriYasChanging(int value);
    partial void OnMusteriYasChanged();
    #endregion
		
		public KullaniciBilgileri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitNO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KayitNO
		{
			get
			{
				return this._KayitNO;
			}
			set
			{
				if ((this._KayitNO != value))
				{
					this.OnKayitNOChanging(value);
					this.SendPropertyChanging();
					this._KayitNO = value;
					this.SendPropertyChanged("KayitNO");
					this.OnKayitNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNO", DbType="Int NOT NULL")]
		public int HesapNO
		{
			get
			{
				return this._HesapNO;
			}
			set
			{
				if ((this._HesapNO != value))
				{
					this.OnHesapNOChanging(value);
					this.SendPropertyChanging();
					this._HesapNO = value;
					this.SendPropertyChanged("HesapNO");
					this.OnHesapNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAd", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MusteriAd
		{
			get
			{
				return this._MusteriAd;
			}
			set
			{
				if ((this._MusteriAd != value))
				{
					this.OnMusteriAdChanging(value);
					this.SendPropertyChanging();
					this._MusteriAd = value;
					this.SendPropertyChanged("MusteriAd");
					this.OnMusteriAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyad", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MusteriSoyad
		{
			get
			{
				return this._MusteriSoyad;
			}
			set
			{
				if ((this._MusteriSoyad != value))
				{
					this.OnMusteriSoyadChanging(value);
					this.SendPropertyChanging();
					this._MusteriSoyad = value;
					this.SendPropertyChanged("MusteriSoyad");
					this.OnMusteriSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriYas", DbType="Int NOT NULL")]
		public int MusteriYas
		{
			get
			{
				return this._MusteriYas;
			}
			set
			{
				if ((this._MusteriYas != value))
				{
					this.OnMusteriYasChanging(value);
					this.SendPropertyChanging();
					this._MusteriYas = value;
					this.SendPropertyChanged("MusteriYas");
					this.OnMusteriYasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HesapBilgileri")]
	public partial class HesapBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KayitNO;
		
		private int _HesapNO;
		
		private int _Bakiye;
		
		private int _ArtiPara;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKayitNOChanging(int value);
    partial void OnKayitNOChanged();
    partial void OnHesapNOChanging(int value);
    partial void OnHesapNOChanged();
    partial void OnBakiyeChanging(int value);
    partial void OnBakiyeChanged();
    partial void OnArtiParaChanging(int value);
    partial void OnArtiParaChanged();
    #endregion
		
		public HesapBilgileri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitNO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KayitNO
		{
			get
			{
				return this._KayitNO;
			}
			set
			{
				if ((this._KayitNO != value))
				{
					this.OnKayitNOChanging(value);
					this.SendPropertyChanging();
					this._KayitNO = value;
					this.SendPropertyChanged("KayitNO");
					this.OnKayitNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNO", DbType="Int NOT NULL")]
		public int HesapNO
		{
			get
			{
				return this._HesapNO;
			}
			set
			{
				if ((this._HesapNO != value))
				{
					this.OnHesapNOChanging(value);
					this.SendPropertyChanging();
					this._HesapNO = value;
					this.SendPropertyChanged("HesapNO");
					this.OnHesapNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bakiye", DbType="Int NOT NULL")]
		public int Bakiye
		{
			get
			{
				return this._Bakiye;
			}
			set
			{
				if ((this._Bakiye != value))
				{
					this.OnBakiyeChanging(value);
					this.SendPropertyChanging();
					this._Bakiye = value;
					this.SendPropertyChanged("Bakiye");
					this.OnBakiyeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtiPara", DbType="Int NOT NULL")]
		public int ArtiPara
		{
			get
			{
				return this._ArtiPara;
			}
			set
			{
				if ((this._ArtiPara != value))
				{
					this.OnArtiParaChanging(value);
					this.SendPropertyChanging();
					this._ArtiPara = value;
					this.SendPropertyChanged("ArtiPara");
					this.OnArtiParaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
